import { writeFileSync } from 'node:fs';
import {
  colors,
  focus,
  fonts,
  fontSizes,
  layout,
  leading,
  motion,
  rules,
  space,
  tracking,
} from '../src/design/tokens.ts';

const PHONE = 390;
const DESKTOP = 1440;
const ROOT_PX = 16;

const kebab = (name: string) => name.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`);

const round = (value: number) => Number(value.toFixed(4));

const fluid = ({ min, max }: { min: number; max: number }) => {
  if (min === max) return `${round(min / ROOT_PX)}rem`;
  const slope = (max - min) / (DESKTOP - PHONE);
  const intercept = min - slope * PHONE;
  return `clamp(${round(min / ROOT_PX)}rem, ${round(intercept / ROOT_PX)}rem + ${round(slope * 100)}vw, ${round(max / ROOT_PX)}rem)`;
};

const group = (prefix: string, values: Record<string, string>) =>
  Object.entries(values).map(([name, value]) => `  --${prefix}-${kebab(name)}: ${value};`);

const fluidGroup = (prefix: string, values: Record<string, { min: number; max: number }>) =>
  Object.entries(values).map(([name, value]) => `  --${prefix}-${kebab(name)}: ${fluid(value)};`);

const { gutter, ...fixedLayout } = layout;

const lines = [
  '/* Generated by scripts/build-tokens.ts from src/design/tokens.ts. Edit the source, then run `pnpm tokens`. */',
  ':root {',
  ...group('color', colors),
  ...group('font', fonts),
  ...fluidGroup('size', fontSizes),
  ...group('tracking', tracking),
  ...group('leading', leading),
  ...group('space', space),
  `  --layout-gutter: ${fluid(gutter)};`,
  ...group('layout', fixedLayout),
  ...group('rule', rules),
  ...group('focus', focus),
  ...group('motion', motion),
  '}',
  '',
];

writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), lines.join('\n'));
