import { existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { fromFile } from '@capsizecss/unpack/fs';

type Metrics = Awaited<ReturnType<typeof fromFile>>;

type Variant = 'regular' | '700' | 'italic';

interface Face {
  file: string;
  variant: Variant;
  weight: string;
  style?: 'italic';
}

interface Fallback {
  label: string;
  metrics: string;
  system?: { file: string; postscriptNames: Record<Variant, string> };
}

interface Family {
  name: string;
  faces: Face[];
  fallbacks: Fallback[];
}

const families: Family[] = [
  {
    name: 'Redaction',
    faces: [
      { file: 'redaction-regular.woff2', variant: 'regular', weight: '400' },
      { file: 'redaction-bold.woff2', variant: '700', weight: '500 700' },
    ],
    fallbacks: [
      { label: 'Georgia', metrics: 'georgia' },
      { label: 'Times', metrics: 'timesNewRoman' },
      { label: 'Noto', metrics: 'notoSerif' },
    ],
  },
  {
    name: 'Uncut Sans',
    faces: [
      { file: 'uncut-sans-regular.woff2', variant: 'regular', weight: '400' },
      { file: 'uncut-sans-bold.woff2', variant: '700', weight: '700' },
    ],
    fallbacks: [
      { label: 'Helvetica', metrics: 'helveticaNeue' },
      { label: 'Arial', metrics: 'arial' },
      { label: 'Roboto', metrics: 'roboto' },
    ],
  },
  {
    name: 'Sozzer Mono',
    faces: [
      { file: 'sozzer-mono-regular.woff2', variant: 'regular', weight: '400' },
      { file: 'sozzer-mono-bold.woff2', variant: '700', weight: '700' },
      { file: 'sozzer-mono-italic.woff2', variant: 'italic', weight: '400', style: 'italic' },
    ],
    fallbacks: [
      {
        label: 'Menlo',
        metrics: 'menlo',
        system: {
          file: '/System/Library/Fonts/Menlo.ttc',
          postscriptNames: { regular: 'Menlo-Regular', 700: 'Menlo-Bold', italic: 'Menlo-Italic' },
        },
      },
      { label: 'Courier', metrics: 'courierNew' },
      { label: 'Noto', metrics: 'notoSansMono' },
    ],
  },
];

const fontsDir = new URL('../src/assets/fonts/', import.meta.url);

const capsizeMetrics = async (name: string, variant: Variant) => {
  try {
    const module = (await import(`@capsizecss/metrics/${name}/${variant}`)) as { default: Metrics };
    return module.default;
  } catch {
    return undefined;
  }
};

// Not every system font is in @capsizecss/metrics (Menlo isn't), so read the installed file when there is one.
const systemMetrics = ({ system }: Fallback, variant: Variant) =>
  system && existsSync(system.file)
    ? fromFile(system.file, { postscriptName: system.postscriptNames[variant] })
    : undefined;

const percent = (value: number) => `${Number((value * 100).toFixed(2))}%`;

// Capsize's method: match the average character width, then express the font's vertical metrics in the fallback's scaled em.
const overrides = (font: Metrics, fallback: Metrics) => {
  const sizeAdjust =
    font.subsets.latin.xWidthAvg /
    font.unitsPerEm /
    (fallback.subsets.latin.xWidthAvg / fallback.unitsPerEm);
  const em = font.unitsPerEm * sizeAdjust;
  return {
    'size-adjust': percent(sizeAdjust),
    'ascent-override': percent(font.ascent / em),
    'descent-override': percent(Math.abs(font.descent) / em),
    'line-gap-override': percent(font.lineGap / em),
  };
};

const fontFace = (family: string, face: Face, font: Metrics, fallback: Metrics) => {
  const names = [...new Set([fallback.fullName, fallback.postscriptName])];
  const descriptors = {
    'font-family': `'${family}'`,
    src: names.map(name => `local('${name}')`).join(', '),
    'font-weight': face.weight,
    ...(face.style && { 'font-style': face.style }),
    ...overrides(font, fallback),
  };
  const lines = Object.entries(descriptors).map(([key, value]) => `  ${key}: ${value};`);
  return ['@font-face {', ...lines, '}'].join('\n');
};

const rules: string[] = [];

for (const family of families) {
  for (const face of family.faces) {
    const font = await fromFile(fileURLToPath(new URL(face.file, fontsDir)));
    for (const fallback of family.fallbacks) {
      const metrics =
        (await capsizeMetrics(fallback.metrics, face.variant)) ??
        (await systemMetrics(fallback, face.variant));
      if (!metrics) continue;
      rules.push(fontFace(`${family.name} Fallback ${fallback.label}`, face, font, metrics));
    }
  }
}

const header =
  '/* Generated by scripts/build-font-fallbacks.ts from the files in src/assets/fonts. Run `pnpm fonts` to regenerate. */';

writeFileSync(
  new URL('../src/styles/fonts-fallbacks.css', import.meta.url),
  `${[header, ...rules].join('\n\n')}\n`,
);
